services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "3000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  localstack:
    image: localstack/localstack:3.4
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=cloudformation,s3,sts,lambda,apigateway,dynamodb,iam,logs,ec2,elasticache,ssm
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=local
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_data:/var/lib/localstack"

  web:
    build: ./backend
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      dynamodb:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION_NAME=us-east-1
      - DYNAMODB_ENDPOINT_URL=http://dynamodb:8000
      - REDIS_URL=redis://redis:6379/1
      - ECOMMERCE_CACHE_TTL_SECONDS=60
      - ENVIRONMENT=development
      - DEBUG=True

  frontend:
    build: ./frontend
    container_name: ecocart_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - web
    environment:
      - VITE_API_URL=http://localhost:8000/api
